### ISSUE TITLE
Sunglasses don't scale correctly

### ISSUE THREAD

**Issue by mfarberbrodsky** [hackclub/summer-site#15]
Small issue, sunglasses don't work well with weird scaling. Here's an example:
![image](https://user-images.githubusercontent.com/52815346/83357347-7e605e00-a374-11ea-8487-0a4b312e8105.png)
(btw the sunglasses are really fun)

**Comment by lachlanjc** [comment]
Yep, thanks for pointing out. Will try to fix soon!

**Comment by lachlanjc** [comment]
This is totally an issue, but not planning to fix it before replacing the page. Thanks though.
