### ISSUE TITLE
Scrapbook Hidden

### ISSUE THREAD

**Issue by sampoder** [hackclub/summer-site#30]
![Screen Shot 2020-07-01 at 4 15 49 PM](https://user-images.githubusercontent.com/39828164/86220462-32dce200-bbb6-11ea-8837-9f943704bb32.png)

**Comment by sampoder** [comment]
Based on [this deployment](https://vercel.com/hackclub/summer/gvwyq4gqm/hackclub.dev) now being broken, this is likely due to a change on Scrappy / Scrapbook.

**Comment by sampoder** [comment]
@lachlanjc do you know if anything changed on the scrapbook site?

**Comment by lachlanjc** [comment]
Fixed in #29

**Comment by sampoder** [comment]
great!
