### ISSUE TITLE
Gradient Changing on Devices

### ISSUE THREAD

**Issue by sampoder** [hackclub/summer-site#32]
![Screen Shot 2020-07-01 at 6 03 29 PM](https://user-images.githubusercontent.com/39828164/86231526-4774a680-bbc5-11ea-8b1c-d3dc56a0745a.png)
![Screen Shot 2020-07-01 at 6 03 19 PM](https://user-images.githubusercontent.com/39828164/86231546-4cd1f100-bbc5-11ea-9bca-31c088f3c14b.png)

I don't know if this was intentional but just dropping it here

**Comment by lachlanjc** [comment]
Yep, that was purposeful to improve readability on mobile :)

**Comment by sampoder** [comment]
ahh thats smart!
