### ISSUE TITLE
Arduino Logo is Social Distancing

### ISSUE THREAD

**Issue by sampoder** [hackclub/summer-site#34]
![Screen Shot 2020-07-01 at 6 08 47 PM](https://user-images.githubusercontent.com/39828164/86232016-f913d780-bbc5-11ea-9ece-cac80261429d.png)

This is big time nitpicking I know

**Comment by sampoder** [comment]
To add more serious context: The Arduino logo barely stands our here and they've been a major supporter of the program. Though I understand its a square logo, yep

**Comment by lachlanjc** [comment]
The logos are pretty good size already, though I agree that GitHub’s letters are way bigger. What are you thinking as a solution?

**Comment by sampoder** [comment]
What I was originally thinking was making the like grid boxes the same size as the image, but I couldn't really work that out (I'll explore it a bit more). I think the GitHub is alright, coz it's like the big partner, so big partner = bigger logo?
