### ISSUE TITLE
Graphics Not Loading

### ISSUE THREAD

**Issue by sampoder** [hackclub/summer-site#37]
<img width="1427" alt="Screen Shot 2020-07-03 at 18 16 05" src="https://user-images.githubusercontent.com/39828164/86502596-8f6b1780-bdd7-11ea-88dd-a5c6df9fe1d5.png">

I will take a look later today

**Comment by sampoder** [comment]
Fixed in https://github.com/hackclub/summer-site/commit/218214f4786b4b1570138f2a7d88901170dbfce8

**Comment by lachlanjc** [comment]
Super appreciate you taking care of this!
