### ISSUE TITLE
Background Slack Video very small

### ISSUE THREAD

**Issue by sampoder** [hackclub/summer-site#39]
Only happens on https://hackclub.com

<img width="1440" alt="Screenshot 2020-07-04 at 9 14 23 PM" src="https://user-images.githubusercontent.com/39828164/86513641-78134500-be3e-11ea-9b2c-fc2681b2949b.png">

Using Safari on the Mac

**Comment by sampoder** [comment]
Seems to be an isolated issue

**Comment by lachlanjc** [comment]
I can’t reproduce this issue—I’m going to close for now, unless you’re still getting it or others can reproduce?

**Comment by sampoder** [comment]
ya I'm only getting it on safari

**Comment by sampoder** [comment]
but I'm still getting it

**Comment by sampoder** [comment]
just kinda weird

**Comment by sampoder** [comment]
update: this was safari's fault (naughty safari) safari got updated and fixed so let this issue die
